repositories:
  - name: jupyterhub
    url: https://hub.jupyter.org/helm-chart/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: jupyterhub
    namespace: jupyterhub
    chart: jupyterhub/jupyterhub
    version: 4.2.0
    values:
      - values/jupyterhub.yaml
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.3
    values:
      - values/ingress-nginx.yaml